sudo: required
services:
  - docker
language: bash

# Update Docker Engine
before_install:
  - sudo apt-get update
  - sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-engine

script:
  - docker build --tag praekeltfoundation/vumi .

after_script:
  - docker images
