dist: xenial
services: docker
language: python

env:
  global:
    - IMAGE_NAME=praekeltfoundation/vumi
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "l0qMv7w+m/TOF3TLz8ZF5HJFN1dIkmVwK824BaokWa8vM5QNHtR7PM89cCshcTmKJFE5Lfp2NUcTK9G6+uJrC4+Vk0DPatDk+PmhuWwTufSj6d7sHnDCFXlD7ZbVooKP+K5F+ltxlInS5if9csozZz6kVIi8UW3YjYXQiF+wWY59ywsWRQ9gxGBxiJUQEDJOK8F9XIrFLqqx6B67QgoWMPfNivxhc6kgIeoT1N8YqOqRlhV4Sz0PzA3Knxb6/b7zZMcC5OSbNyLxv1X8veMagJsHKk2AqthAPzc6nMzHi+GG1vhQl0NV6WbmQgDcPnV5ZauiUu4VQpzciepnzkq1OEmcPhdROvHzfszFQoRRFUrXd24TpWwehfNw2fBEGqTRji4zSrBfKXlrJkvmR5XSnyv/YNBapA85Jh67qZTTx4ckiG6GQ+8Zm2z75vyEvtuQ5XLfD22wyljeQE9aUJVN/eXv1RE/yI1Qm1VXh+2Z2F4vKzaILjWQVf81PMDvJgn9QqAypiuZEYqVKPVjlN4ceoSptYyfQ541HrUAYG3Op8ujbY/0j1O6CPWtMuKu+KroI75b+GhUlLPZ/7a/IB4la4ZiugKQVkSz8CsRlrRsRrYQNSUkWdMKHCpQkfPlfmvhTYt4g+cPRZJ85M7BJ/ewXGOqF9oHnUHQvPjL35Qgwyk="
  matrix:
    - VARIANT=python TAG_DEFAULT=1
    - VARIANT=pypy   TAG_DEFAULT=

install: [] # Don't do a pip install (default for Travis Python environment)

before_script:
  - version="$(sed -nE 's/^vumi==([0-9\.]+)/\1/p' requirements.txt)"
  - echo "Building image '$IMAGE_NAME' for Vumi version '$version'..."
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" -t "$IMAGE_NAME" --build-arg VARIANT="$VARIANT" .
  - ./test.sh "$IMAGE_NAME"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd --tag "$VARIANT" ${TAG_DEFAULT:+''} --version "$version" --version-latest "$IMAGE_NAME"
  on:
    branch: master
